### ISSUE TITLE
Addl methods for AsyncCrypto needed

### ISSUE THREAD

**Issue by willy-b** [dattnetwork/datt-node#24]
Need following additional functionality in AsyncCrypto:

Signature verification
- bitcore.crypto.ECDSA.verify

Signature constructors
- bitcore.crypto.Signature.fromString
- bitcore.crypto.Signature.fromBuffer

PubKey and Address validation
- validatePubKey
- validateAddress

**Comment by ryanxcharles** [comment]
I'm not sure all these actually have to be async. ECDSA.verify definitely does, because it uses point multiplication, which is the slowest operation. However, parsing a signature from a string or a buffer probably doesn't do anything slow. It just parses the bits of the signature and creates new big numbers. It probably doesn't do any hashing or point multiplication. (However, perhaps bitcore does something unexpected inside those methods, in which case we would need to put them in the async module).

I'm not sure about validatePubkey or validateAddress. They may or may not do point multiplication or hashing. If validatePubkey rederives the public key from a private key, then it needs to be async. If it just parses it and makes sure that is parses validly, that shouldn't be slow. validateAddress is potentially slow if it recomputes the hash function, which it probably does.

Things to keep in mind:
- Point multiplication is the slowest operation. Anything that uses point multiplication, including signing/verifying, deriving a public key from a private key, or any of the BIP32 operations, need to be async.
- Hashing is slow, and can be as slow or slower than point multiplication on large data, so that needs to be async.
- Any operations that use point multiplication or hashing need to be async. This is tricky, because it's not always obvious what uses slow crypto. Converting a bitcoin address to a string is one. This involves a hash function, and therefore should be async.
- Right now I can't think of crypto elements besides point multiplication and hashing that need to be async, but there may be others, so if we discover other slow things we will need to make those async as well.

**Comment by willy-b** [comment]
Thanks for the feedback. Just going to push ECDSA verify (Signature verification) right now then. Almost there, just writing test.
